### ISSUE TITLE
Bangs::ProhibitFlagComments should check for entire words

### ISSUE THREAD

**Issue by petdance** [petdance/perl-critic-bangs#21]
Something like `SITE_XXX` shouldn't trigger the `XXX` prohibition.

**Comment by Amorymeltzer** [comment]
Presumably something like `if ( $elem->content() =~ /\b$keyword\b/ )` would work, but then you get into the `quotemeta` realm.

**Comment by petdance** [comment]
Sure, that would be good.  Thanks.  Please make sure it has updated tests for it as well.

**Comment by petdance** [comment]
And `/\b\Q$keyword\E\b` wouldn't be so bad, right?

**Comment by Amorymeltzer** [comment]
Indeed no!  That's what I'd tossed together this morning.

**Comment by petdance** [comment]
Another example: "BUG" catching "BUGS", which is a common heading.
